In [1]:
s = 'abcdse'
s[0]

'a'

In [3]:
''.join(['1','w','s'][:2])

'1w'

In [2]:
p = 1
for i in range(p):
    print(i)
    p=2

0


In [1]:
a = 1
def test(x):
    x += 1
test(a)
a

1

In [6]:
a = [1]
x = a
a = a.append(2)
x

[1, 2]

In [1]:
a = [[1]]
x = a[:] # 浅拷贝
a[0] = a[0].append(2)
x

[[1, 2]]

In [4]:
sum([1,2,3][:2])

3

In [1]:
a = None
if a == None:
    print(22)

22


In [10]:
d = [[0]*5]*5
d[0][1] = 1
d

[[0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 1, 0, 0, 0]]

In [3]:
print(chr(122))

z


In [3]:
str([1,2,3])

'[1, 2, 3]'

In [6]:
a = {'A':1}
b = {'A':5}

tuple(a.items())<=tuple(b.items())

True

In [14]:
a = [1,2,3,4,5,7,8,9,11,14]

target = 5

l=0
r=len(a)-1
ans = -1
#定义区间[l,r]
while l<=r:
    mid = (l+r)//2
    if a[mid]>target:
        l = mid+1
    elif a[mid]<target:
        r=mid-1
    else:
        ans = mid
        break
ans

4

In [1]:
a = [[1,2],[2,1],[0,1]]
sorted(a)

[[0, 1], [1, 2], [2, 1]]

In [1]:
a=set([1,1,2,3,3,4])
a.pop()
a.pop()
a.pop()
a.pop()

4

In [2]:
import torch

a = torch.randn(2,3)
b = torch.randn(2,3)
a, b

(tensor([[ 0.7859, -1.0265, -1.4303],
         [-0.0393, -0.8960,  1.4704]]),
 tensor([[ 0.4478, -0.2138,  1.0124],
         [-1.2564,  0.7231, -1.4886]]))

In [6]:
a*b

tensor([[ 0.3520,  0.2195, -1.4481],
        [ 0.0493, -0.6479, -2.1889]])

In [8]:
a = [-10, -10, -5, 0, 1, 5, 8, 10]

left = 0
right = len(a)-1

num = 0
while left<=right:
    if a[left]+a[right]==0:
        num += 1
        left += 1
        right -= 1

        while left>0 and a[left]==a[left-1]:
            left += 1
        while right<len(a)-1 and a[right]==a[right+1]:     
            right -= 1
    elif a[left]+a[right]<0:
        num +=1
        left+=1

        while left>0 and a[left]==a[left-1]:
            left += 1
    else:
        num += 1
        right-=1
        while right<len(a)-1 and a[right]==a[right+1]:     
            right -= 1

num


5

In [10]:
nums = [1,2,3,5,7,9]

left = 0
right = len(nums)-1
target = 10

while left<=right:
    mid = (left+right)//2

    if nums[mid]<target:
        left = mid + 1
    else:
        right = mid -1

# left-第一个大于等于target的   right-第一个小于target的
left, right

(6, 5)

In [11]:
nums = [1,2,3,5,7,9]

left = 0
right = len(nums)-1
target = 10

while left<=right:
    mid = (left+right)//2

    if nums[mid]<=target:
        left = mid + 1
    else:
        right = mid -1

# left-第一个大于target的   right-第一个小于等于target的
left, right

(6, 5)

In [7]:
class Solution(object):
    def nextPermutation(self, nums):
        res = []
        path = []

        def dfs(idx):
            if len(path) == len(nums):
                res.append(path[:])
            
            for i in range(idx, len(nums)):
                path.append(nums[i])
                nums[i], nums[idx] = nums[idx], nums[i]
                dfs(idx+1)
                path.pop()
                nums[i], nums[idx] = nums[idx], nums[i]
        
        dfs(0)
        return res
print(Solution().nextPermutation([1,2,3]))

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 2, 1], [3, 1, 2]]


In [11]:
a = [0,1,3]

b = [0,1,0]
b[-1] = 3

a==b

True

In [10]:
m = [[0,1],[2,3]]
m[:][1] = [0,0]
m

[[0, 1], [2, 3]]

In [ ]:
# Definition for singly-linked list.
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
class Solution:
    def sortList(self, head):
        ### 归并排序
        def sort(left):
            if not left or not left.next:
                return left

            # 从中间拆分
            fast = left
            slow = left
            while fast and fast.next:
                pre = slow
                slow = slow.next
                fast = fast.next.next
            mid = pre
            temp = mid.next
            mid.next = None

            l = sort(left)
            r = sort(temp)
            
            # 合并
            bin_head = ListNode()
            p = bin_head
            p1 = l
            p2 = r

            while p1 or p2:
                if p1 and p2:
                    if p1.val <= p2.val:
                        p.next = p1
                        p1 = p1.next
                    else:
                        p.next = p2
                        p2 = p2.next
                elif p1:
                    p.next = p1
                    p1 = p1.next
                else:
                    p.next = p2
                    p2 = p2.next

                p = p.next
            
            return bin_head.next

        return sort(head)



a = ListNode(4)
b = ListNode(2)
c = ListNode(1)
d = ListNode(3)

a.next = b
b.next = c
c.next = d

Solution().sortList(a)

In [4]:
int(6/-132)

0